name: Build & Push Application Containers
on:
  workflow_dispatch:
  push:
#    branches:
#      - main
jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Build the container Images and push to DockerHub
      run: |
        docker buildx build -f Dockerfile \
          --platform linux/amd64,linux/arm64,linux/386,linux/ppc64le,linux/s390x \
          -t "$DH_USER/$REPO:advicemate" \
          --push .
    